version: '3.8'
services:
  payments:
    build:
      context: ./payments-service
    ports:
      - "8081:8081"
    depends_on:
      - bank

  bank:
    build:
      context: ./bank-simulator
    ports:
      - "8082:8082"
